apiVersion: apps/v1
kind: Deployment
metadata:
  name: netshoot-deployment
  labels:
    app: netshoot
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: netshoot
  template:
    metadata:
      labels:
        app: netshoot
    spec:
      containers:
        - name: netshoot
          image: nicolaka/netshoot
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c"]
          args:
            [
              'while true; do echo -e "HTTP/1.0 200 OK\r\n\r\nopen_socket_connections $(($(ss -ta state big | wc -l) - 1))" | nc -q 0 -l -p 9090; done',
            ]
          resources:
            requests: {}
            limits:
              memory: 1Gi
              cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: netshoot
  labels:
    app: netshoot
spec:
  selector:
    app: netshoot
  ports:
    - name: metrics
      port: 9090
      targetPort: 9090
