apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: netshoot
  labels:
    app: netshoot
spec:
  selector:
    matchLabels:
      app: netshoot
  endpoints:
    - port: metrics # works for different port numbers as long as the name matches
      interval: 10s # scrape the endpoint every 10 seconds
